version: '3.8'

services:
  postgres_db:
    image: ibrahim966/feewock-database:latest
    container_name: feewock-postgres
    environment:
      POSTGRES_DB: 'feewock1_db'
      POSTGRES_USER: 'feewock1_user'  
      POSTGRES_PASSWORD: 'feewock1_123'
    volumes:
      - postgres_data:/var/lib/postgresql/data


  web:
    build: 
      # context: ./server/feewock
      dockerfile: Dockerfile
    command: bash -c "daphne -b 0.0.0.0 -p 8001 feewock.asgi:application"
    image: ibrahim966/feewock-server
    container_name: feewock_container  
    ports:
      - "8001:8001"
    depends_on:
      - postgres_db
      - redis
    volumes:
      - .:/web
      - static_volume:/app/media
      - ./static:/app/static
      


  redis:
    image: ibrahim966/feewock-redis:latest
    ports:
      - "6379:6379"


volumes:
  postgres_data:
  static_volume:

